# render.yaml
services:
  - type: web
    name: sun-gps-attendance
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SQLSERVER_CONN_STR
        value: Driver={SQL Server};Server=DESKTOP-LF6CHGA\SQLEXPRESS;Database=Sun_Database;Trusted_Connection=yes;