services:
  - type: web
    name: SUN_Test
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        sync: false
